{
 "title": "Measuring the golden signal",
 "time": { "from": "2021-11-08T22:19:54.481Z", "to": "2021-11-08T22:20:56.550Z" },
 "panels": [
  {
   "title": "Rate (R): Number of requests per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Requests per minute"
    }
   ]
  },
  {
   "title": "Errors (E): The number of failed requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errors (E): The number of failed requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes / 1024 )"
    }
   ]
  }
 ]
}